//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionsModule.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmittedAnswer
    {
        public int id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<int> question_id { get; set; }
        public Nullable<int> option_id { get; set; }
        public Nullable<int> submitted_option_id { get; set; }
    
        public virtual Option Option { get; set; }
        public virtual Question Question { get; set; }
        public virtual Tbl_Emp Tbl_Emp { get; set; }
    }
}
